services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: admin_order_service
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
